version: '3'

services:
  apache:
    build: ./docker/apache
    container_name: apache
    restart: always
    volumes:
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/symbiota
    depends_on:
      - mariadb
    ports:
      - 80:80

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symbiota
    ports:
      - 3310:3306
